### PR TITLE
added validation to ticketSchema

### LINKED ISSUE #13: Add Validations to ticketSchema
Currently, the `ticketSchema` lacks necessary validations to ensure data integrity. Adding validations will help prevent invalid or inconsistent data from being saved to the database.  

### Some Suggested Validations:  
1. **Title**:  
   - Required field.  
   - Should be `unique`. 

2. **Category**:  
   - Must be one of the predefined categories from `EditTicketForm.tsx`.  

3. **Priority**:  
   - Must be a number.  
   - Range: [1, 5].  

4. **Progress**:  
   - Must be a number.  
   - Range: [0, 100].  

You can use MongoDB's built-in validators like `required`, `min`, `max` and `enum`, wherever applicable.

### PR DESCRIPTION
**Pull request by disvid**
### Related Issue  
Closes #13   

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
Adds validations that will help prevent invalid or inconsistent data from being saved to the database.

### Implementation Details  
required changes have been made in app/models/Ticket.js .

### CODE REVIEW

**Comment by disvid** [comment]
@AyushDharDubey sir can you please review this one?

**Comment by AyushDharDubey** [comment]
please incorporate the suggested changes first

**Comment by disvid** [comment]
@AyushDharDubey sir which changes?

**Comment by AyushDharDubey** [comment]
> @AyushDharDubey sir which changes?

@disvid, are you able to access [these reviews](https://github.com/IMGIITRoorkee/Ticketify/pull/50/files/3bd82e917884ffc78d7779a0660a8c6f58dc321b)?

**Comment by disvid** [comment]
@AyushDharDubey no sir, no reviews are visible.

**Comment by AyushDharDubey** [comment]
> @AyushDharDubey no sir, no reviews are visible.

that's strange,
anyways, i wanted you to

1. allow some more categories options in the enum which have been added via #45
2. modify the enum for progress field to allow [0, 10, 20, ....] to ensure strict type safety and prevent intruders from setting illegal values.

**Comment by AyushDharDubey** [comment]
Thanks @disvid 
i can see that the PR successfully addresses the issue and is good to be merged.

**Pull request merged**
