### PR TITLE
Resolved issue #3

### LINKED ISSUE #3: Status is not visible
When you will see your tickets on dashboard you will not be able to see status of your ticket.
Add the status option where you can see current status of your  ticket.

### PR DESCRIPTION
**Pull request by MadhavDhall**
### Related Issue  
Closes #3 

### Type of Change
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
Below the progress bar in the ticket card status of the ticket gets displayed.
if the status is **"done"** then there is no display of the progress bar and Background color of the ticket card changes according to status of the ticket.

### Implementation Details  
Below the progress bar in the ticket card status of the ticket gets displayed.
if the status is **"done"** then there is no display of the progress bar and Background color of the ticket card changes according to status of the ticket. 
This is done with help of status attribute of the ticket fetched from the DB.

### Demo  

https://github.com/user-attachments/assets/c45623ab-6229-45de-9af5-5d0255188748

### CODE REVIEW

**Comment by AyushDharDubey** [comment]
Hi @MadhavDhall, good work, i can see your PR can fix the issue

feel free to add your name on [CONTRIBUTORS.md](https://github.com/IMGIITRoorkee/Ticketify/blob/master/CONTRIBUTORS.md) and then we can proceed to merge the PR

**Comment by MadhavDhall** [comment]
Done @AyushDharDubey sir. Kindly merge both pull requests.

**Comment by AyushDharDubey** [comment]
please commit the change on issue#3 branch only,
a new PR should not be opened just for updating CONTRIBUTORS.md

**Comment by MadhavDhall** [comment]
ok sir done as you said
Sorry @AyushDharDubey i was not able to understand what you meant earlier.
Now i have updated contributors file and push the changes in same PR.

**Comment by MadhavDhall** [comment]
Hi @AyushDharDubey 
This issue was resolved yesterday by PR getting merged. But in the leaderboard I have not received points for this particular PR although I have received points for the PR which was merged after this one.
I request to kindly see if this is something related to code error or human mistake or something.
Thanks

**Comment by AyushDharDubey** [comment]
yes there is indeed some issue with leaderboard,
we are working on it
if it is not updated in 1-2 days please raise the issue again on our Discord channel

**Pull request merged**
