### PR TITLE
Adding a view by option 

### LINKED ISSUE #56: Add a View by option.
Adding a View by option with the following values:

- Category

- Status

### PR DESCRIPTION
**Pull request by disvid**
Closes #56  

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
Adding a View by option with the following values:

- Category

- Status

### Demo  
[Screencast from 2024-12-22 03-11-39.webm](https://github.com/user-attachments/assets/9436a687-e51d-4c5a-a724-a1ea0cf05891)

### CODE REVIEW

**Comment by disvid** [comment]
@iamgoeldhruv @AyushDharDubey  let's merge because there will be merge conflict post merging this PR in other PRs.

**Comment by AyushDharDubey** [comment]
good work @disvid,
the changes are solid, and you've earned the opportunity to make the call on #51. #58 will be merged shortly, stay tuned.

you have two options: either we can merge #51, or, we can close #51 and #5 and mark'em as completed in #58. If you want it merged, you need to resolve the merge conflict immediately. Once that's handled, we’ll proceed with merging both PRs in sequence.

**Comment by disvid** [comment]
@AyushDharDubey Done sir , the conflicts have been resolved, let's merge them in sequence now.

**Comment by disvid** [comment]
@AyushDharDubey sir please merge now 🙏🙏, had to resolve conflicts again.

**Pull request merged**
