### PR TITLE
issue_29 Create a Custom 404 Error Page for Better UX

### LINKED ISSUE #29: Create a Custom 404 Error Page for Better UX
The current project doesn't have a custom 404 error page, which can lead to a poor user experience if users try to navigate to a non-existent page. Create a custom "Not Found" page to display when a user attempts to navigate to an invalid route in the application. You can refer to the [Next.js Documentation](https://nextjs.org/docs/app/api-reference/file-conventions/not-found) for app routing and best practices on creating custom error pages.

### PR DESCRIPTION
**Pull request by disvid**
### Related Issue  
Closes #29 
### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
custom 404 error page has been created for non-existent pages.

### Demo  
Screenshot from 2024-12-20 20-44-08

### CODE REVIEW

**Comment by AyushDharDubey** [comment]
Hi @disvid, Thank you for submitting.

1. Please restore `SAMPLE.env.local`
2. Your 404.js will not load and **is not** loading, as evident from your Demo screenshot. Dig into the [docs](https://nextjs.org/docs/app/api-reference/file-conventions/not-found) and figure out why

**Comment by disvid** [comment]
@AyushDharDubey Sir, I have restored the SAMPLE.env.local file and the 404 error page is now working, please check.
thankyou.

**Comment by AyushDharDubey** [comment]
Hi @disvid,

we encourage your efforts on the issue, but your fix is not working on my system, and I’m unable to see why it should work logically based on the current implementations

If you believe this issue is specific to my setup, please attach a corresponding screenshot or other relevant proof of the fix in action for further clarification.

Again if you need any help or hints on why the issue is not working, feel free to reach out to us.

**Comment by disvid** [comment]
@AyushDharDubey sir i have made a change, and its working now. i have added a video below.
[Screencast from 2024-12-23 02-32-04.webm](https://github.com/user-attachments/assets/a29c0536-2e04-45a9-85fd-34ec2a8b2b71)

**Comment by disvid** [comment]
@AyushDharDubey Done sir, made the changes.

**Pull request merged**
