### PR TITLE
added progress markers

### LINKED ISSUE #10: Progress Slider in create ticket can have percentages markers
Progress slider can have a mark of 50% and 100% to easily assess where our status lies rather than choosing any point on the line.

### PR DESCRIPTION
**Pull request by disvid**
### Related Issue  
Closes #10 

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
Progress slider can have a mark of 50 and 100 to easily assess where our status lies rather than choosing any point on the line.

### Implementation Details  
required changes have been done in app/(components)/EditTicketForm.jsx this file.

### Demo  
Screenshot from 2024-12-21 01-42-10

### CODE REVIEW

**Comment by iamgoeldhruv** [comment]
Divide it into 10 parts

**Comment by disvid** [comment]
@iamgoeldhruv means i should put markers at 0,10,20,...,100?

**Comment by iamgoeldhruv** [comment]
@disvid yess exactly

**Comment by disvid** [comment]
@iamgoeldhruv okay sure sir.

**Comment by disvid** [comment]
@iamgoeldhruv done sir.

**Pull request merged**
