### PR TITLE
Created automatic pull request template

### LINKED ISSUE #79: Create Automatic PR template
Create a feature for automatic PR template when creating a new PR , as it is tedious to copy paste it every time.

### PR DESCRIPTION
**Pull request by disvid**
### Related Issue  
Closes #79 & #86

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
Added automatic ISSUE and PR TEMPLATE, so that its easy for contributors to create a new pull request/issue.

### Implementation Details  
Required files/folders have been added in .github folder.

### CODE REVIEW

**Comment by AyushDharDubey** [comment]
Hi @disvid,

please make sure that your PR aligns with our community guidelines.
kindly update your PR description by tonight at 2359 hours or label it as `draft`. If the updates aren't made by then, we may need to proceed with closing this one.

**Comment by disvid** [comment]
@AyushDharDubey  done sir, i request you to kindly assign me issue #20 & #49

**Comment by AyushDharDubey** [comment]
i feel following section in your issue template is redundant, it is already covered via github

```
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''
```

**Comment by disvid** [comment]
It is not redundant, please check the docs. It won't work without 
```
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''
```

**Comment by AyushDharDubey** [comment]
> @AyushDharDubey It is not redundant, please check the docs. It won't work without -

may you please quote the specific page

**Comment by disvid** [comment]
> > @AyushDharDubey It is not redundant, please check the docs. It won't work without -
> 
> may you please quote the specific page

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository @AyushDharDubey  here you go sir.

**Comment by AyushDharDubey** [comment]
> To automatically set a default issue title, assign the issue to people with read access to the repository, or apply labels to issues raised from the template, use the fields under "Optional additional information." You can also add these details in the issue template with title, labels, or assignees in a YAML frontmatter format.

i assume 
```
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''
```
 refers to the "**Optional additional information**" section. let me know if you believe otherwise.

**Comment by disvid** [comment]
@AyushDharDubey  I think we can remove:
```
title: ''
labels: ''
assignees: ''
```

name: and about: will be helpful and needed
Screenshot from 2024-12-31 00-35-54

**Comment by AyushDharDubey** [comment]
okay, if you insist.
i was just concerned about the assignee's section because, in our event, no issue will be assigned at the time of creation. this makes the field absolutely useless, it will always remain blank and will have to be updated manually later once the issue is assigned.

**Comment by AyushDharDubey** [comment]
the rest looks great
i am proceeding to merge the PR now

**Comment by disvid** [comment]
yes sir i have removed the assignee's section

**Pull request merged**
