### PR TITLE
separates tickets by their status

### LINKED ISSUE #5: New Feature: Seperate tickets based on their status. That is show  done in 1 section and other status options likewise

### PR DESCRIPTION
**Pull request by disvid**
### Related Issue  
Closes #5 

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
separates tickets by their status instead of category.

### Implementation Details  
required changes have been done in app/page.jsx the file.

### Demo  
Screenshot from 2024-12-21 03-45-52

### CODE REVIEW

**Comment by AyushDharDubey** [comment]
Hi @disvid,
although your PR does address the issue statement,
it would be even better if you could add a `View by` option with the following values:
- Category
- Status

would you be able to incorporate this enhancement?

Thanks!

**Comment by disvid** [comment]
@AyushDharDubey  Sure sir, could you please allow me to raise a new issue for the same ?

**Comment by AyushDharDubey** [comment]
@disvid Yes please do

**Comment by disvid** [comment]
@AyushDharDubey Sure, so can we merge this?

**Comment by iamgoeldhruv** [comment]
@disvid You have merge conflicts with base branch. Please fix it.
It could be because you have not synced your codebase with current state of remote repository.
Get the needful done.
Once done we will merge it.

**Comment by disvid** [comment]
@iamgoeldhruv sir the conflicts have been resolved.

**Pull request merged**
