### PR TITLE
Adding a view by option

### LINKED ISSUE #56: Add a View by option.
Adding a View by option with the following values:

- Category

- Status

### PR DESCRIPTION
**Pull request by disvid**
### Related Issue  
Closes #56  

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
Adding a View by option with the following values:

- Category

- Status

### Demo  
[Screencast from 2024-12-22 03-11-39.webm](https://github.com/user-attachments/assets/5005df25-c443-4ef0-a954-b2a84105e179)

### CODE REVIEW

**Comment by AyushDharDubey** [comment]
Hi @disvid thankyou for submitting.
1. Please change the PR title to something meaningful.
2. resolve merge conflict

**Comment by disvid** [comment]
@AyushDharDubey Done sir.

**Comment by AyushDharDubey** [comment]
good work @disvid,
but although your fix is working, we won’t be able to merge this PR as there’s a protocol in place that requires all contributors to adhere to the rules outlined in our [CONTRIBUTORS guide](https://github.com/IMGIITRoorkee/MergeFest-Hacker/blob/main/CONTRIBUTORS.md).

in this regard, please rename your branch to the required format and submit a new PR.

**Comment by disvid** [comment]
@AyushDharDubey Sir, somehow the PR gets closed as soon as i rename the branch, so i am creating a new PR for the same.

**Pull request closed without merging**
