### PR TITLE
added tooltips to icons

### LINKED ISSUE #20: Add Tooltips to Icons
Add tooltips for all icons in the UI wherever necessary

### PR DESCRIPTION
**Pull request by disvid**
Closes #20 

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
Tooltips have been added to home and create new ticket icon.

### Demo  
[Screencast from 2024-12-28 03-40-43.webm](https://github.com/user-attachments/assets/4978a639-8b1b-41fe-afaf-015920a1ad07)

### CODE REVIEW

**Comment by AyushDharDubey** [comment]
Hi @disvid ,

I'm sorry, but we will have to close this PR as the issue was not assigned to you. as previously mentioned, contributors are required to discuss their approach and announce their intention to work on an issue before submitting a pull request.

Please ensure to follow this process and then you may reopen the PR.

**Comment by disvid** [comment]
@AyushDharDubey please review.

**Comment by AyushDharDubey** [comment]
nice @disvid,
this is good enough to close #20

but i wonder, was the package update and the `react-tooltip` package necessary?? it seem to work on my system without the specific change.
in case the change is not necessary, please revert it, a new issue might be created in future to update all the packages.

**Comment by disvid** [comment]
@AyushDharDubey sir i have reverted the change in package.json file , do i also need to do it in package-lock.json?
If yes, could you please guide.

**Comment by AyushDharDubey** [comment]
to restore package-lock.json file
go to the current master branch and download the package-lock.json file and replace the file in your branch with the one from master branch, this should restore the change

otherwise, you may copy the content from master branch and paste it in your branch, this should also work

**Comment by disvid** [comment]
@AyushDharDubey Done sir

**Comment by disvid** [comment]
@AyushDharDubey can you please allow me to solve more easy issues ?

**Comment by AyushDharDubey** [comment]
hi @disvid,

please note that no more than 3 easy issues per repository will be counted toward the score. solving additional easy issues beyond this limit won't contribute to your score, so it would be better to let others have the opportunity to work on them.

however, if any of these issues remain unresolved by the end of the event, you may be allowed to fix them. yet, the leaderboard will still only account the scores for up to 3 easy issues per repository.

**Comment by AyushDharDubey** [comment]
in the meantime, we welcome you to submit your proposals for other open issues.

**Comment by disvid** [comment]
@AyushDharDubey okay sir

**Comment by AyushDharDubey** [comment]
@disvid, you may be allowed to solve the issues raised by yourself, even if those are labelled `easy`. so feel free to propose solutions on any of them if you want to.

**Comment by disvid** [comment]
@AyushDharDubey okay sir thankyou.

**Pull request merged**
